language: node_js
node_js:
  - "6"
addons:
  apt:
    packages:
    - gcc-4.8
before_script:
  - npm install
  - echo '{}' > config/local.json
script: npm test
notifications:
  slack: siliconvalleybootcamp:SnRpv9p0fK5FmSEFa7iVqJAw
