language: node_js
node_js:
  - "6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
before_script:
  - npm install
  - echo '{}' > config/local.json
script: npm test
notifications:
  slack: siliconvalleybootcamp:SnRpv9p0fK5FmSEFa7iVqJAw
