language: node_js
node_js:
  - "6"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8

before_script:
  - npm install -g npm
  - npm install
  - echo '{}' > config/local.json
before_install:
  - sudo apt-get update
  - sudo apt-get install python2.7
script: npm test
notifications:
  slack: siliconvalleybootcamp:SnRpv9p0fK5FmSEFa7iVqJAw
