/* for map */
export const GET_MAP_MARKERS = 'GET_MAP_MARKERS';
export const GET_MAP_MARKERS_SUCCESS = 'GET_MAP_MARKERS_SUCCESS';
export const GET_MAP_MARKERS_FAILURE = 'GET_MAP_MARKERS_FAILURE';
export const ADD_CARD = 'ADD_CARD';
export const SELECT_MAP_MARKER = 'SELECT_MAP_MARKER';
export const ADD_MAP_MARKER = 'ADD_MAP_MARKER';
